spring:
  application:
    name: user-service

  mongodb:
    uri: mongodb+srv://SandeepKarne:SpringBoot123456@cluster0.4lre50d.mongodb.net/?appName=Cluster0
    database: userdb

server:
  port: 8082

